#!/bin/bash

# Use nss_wrapper for compatibility with the official openfoam-docker script
if [ $(id -u) != 0 ] && [ -z "$APPTAINER_ENVIRONMENT" ] && [ -z "$SINGULARITY_ENVIRONMENT" ]; then
    export HOME=/home/openfoam
    export LD_PRELOAD=libnss_wrapper.so
    export NSS_WRAPPER_PASSWD="$(mktemp)"
    export NSS_WRAPPER_GROUP="$(mktemp)"
    echo "openfoam:x:$(id -u):$(id -g):openfoam:$HOME:/bin/bash" > "$NSS_WRAPPER_PASSWD"
    echo "openfoam:x:$(id -g):" > "$NSS_WRAPPER_GROUP"
    mkdir -p "$HOME"
    cd
fi

source /openfoam/profile.rc
exec "$@"
