name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  com-2406:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (slim)
        uses: docker/build-push-action@v6
        with:
          platforms: 'linux/amd64,linux/arm64'
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:slim
            ${{ vars.DOCKERHUB_REPOSITORY }}:com-slim
            ${{ vars.DOCKERHUB_REPOSITORY }}:2406-slim
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          target: slim
          build-args: |
            OPENFOAM_VERSION=2312
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: 'linux/amd64,linux/arm64'
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:latest
            ${{ vars.DOCKERHUB_REPOSITORY }}:com
            ${{ vars.DOCKERHUB_REPOSITORY }}:2406
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          build-args: |
            OPENFOAM_VERSION=2406
  com-2312:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (slim)
        uses: docker/build-push-action@v6
        with:
          platforms: 'linux/amd64,linux/arm64'
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:2312-slim
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          target: slim
          build-args: |
            OPENFOAM_VERSION=2312
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: 'linux/amd64,linux/arm64'
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:2312
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          build-args: |
            OPENFOAM_VERSION=2312
  org-12:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: 'linux/amd64,linux/arm64'
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:org
            ${{ vars.DOCKERHUB_REPOSITORY }}:12
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          target: org
          build-args: |
            OPENFOAM_VERSION=12
  org-11:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: 'linux/amd64,linux/arm64'
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:11
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          target: org
          build-args: |
            OPENFOAM_VERSION=11
