name: Build image

on:
  workflow_call:
    inputs:
      openfoam-version:
        type: string
        required: true
      ubuntu-version:
        type: string
        required: true
      multiplatform:
        type: boolean
        required: false
        default: true
      latest:
        type: boolean
        required: false
        default: false
      push:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      openfoam-version:
        description: OpenFOAM version
        type: string
        required: true
      ubuntu-version:
        description: Ubuntu version
        type: string
        required: true
      multiplatform:
        description: Build multiplatform image including amd64 and arm64
        type: boolean
        required: false
        default: true
      latest:
        description: Also tag as the latest version
        type: boolean
        required: false
        default: false
      push:
        description: Push the built image
        type: boolean
        required: false
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        if: inputs.multiplatform
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ !inputs.push }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (com, slim)
        if: inputs.openfoam-version >= 1000
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.multiplatform && 'linux/amd64,linux/arm64' || '' }}
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ inputs.openfoam-version }}-slim
            ${{ inputs.latest && format('{0}:com-slim,{0}:slim', vars.DOCKERHUB_REPOSITORY) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ inputs.push }}
          target: slim
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
      - name: Build and push (com)
        if: inputs.openfoam-version >= 1000
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.multiplatform && 'linux/amd64,linux/arm64' || '' }}
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ inputs.openfoam-version }}
            ${{ inputs.latest && format('{0}:com,{0}:latest', vars.DOCKERHUB_REPOSITORY) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ inputs.push }}
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
      - name: Build and push (org)
        if: inputs.openfoam-version < 1000
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.multiplatform && 'linux/amd64,linux/arm64' || '' }}
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ inputs.openfoam-version }}
            ${{ inputs.latest && format('{0}:org', vars.DOCKERHUB_REPOSITORY) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ inputs.push }}
          target: org
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
