name: Build image

on:
  workflow_call:
    inputs:
      openfoam-version:
        type: string
        required: true
      ubuntu-version:
        type: string
        required: true
      arm64:
        type: boolean
        required: false
        default: true
      latest:
        type: boolean
        required: false
        default: false
      push:
        type: boolean
        required: false
        default: false
    secrets:
      dockerhub-username:
        required: false
      dockerhub-token:
        required: false
  workflow_dispatch:
    inputs:
      openfoam-version:
        description: OpenFOAM version
        type: string
        required: true
      ubuntu-version:
        description: Ubuntu version
        type: string
        required: true
      arm64:
        description: Build multi-platform image including arm64
        type: boolean
        required: false
        default: true
      latest:
        description: Also tag as the latest version
        type: boolean
        required: false
        default: false
      push:
        description: Push the built image
        type: boolean
        required: false
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up QEMU
        if: inputs.arm64
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        continue-on-error: ${{ !inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ !inputs.push }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username || secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.dockerhub-token || secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (com, slim)
        if: inputs.openfoam-version >= 1000
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.arm64 && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ inputs.openfoam-version }}-slim
            ${{ inputs.latest && format('{0}:com-slim,{0}:slim', vars.DOCKERHUB_REPOSITORY) || '' }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-amd64
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-arm64
          push: ${{ inputs.push }}
          target: slim
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
            BUILDKIT_MULTI_PLATFORM=${{ inputs.arm64 }}
      - name: Build and push (com)
        if: inputs.openfoam-version >= 1000
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.arm64 && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ inputs.openfoam-version }}
            ${{ inputs.latest && format('{0}:com,{0}:latest', vars.DOCKERHUB_REPOSITORY) || '' }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-amd64
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-arm64
          push: ${{ inputs.push }}
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
            BUILDKIT_MULTI_PLATFORM=${{ inputs.arm64 }}
      - name: Push build cache (com, amd64)
        if: inputs.openfoam-version >= 1000 && inputs.push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-amd64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-amd64,mode=max
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
      - name: Push build cache (com, arm64)
        if: inputs.openfoam-version >= 1000 && inputs.arm64 && inputs.push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-arm64,mode=max
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
      - name: Build and push (org)
        if: inputs.openfoam-version < 1000
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ inputs.arm64 && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: |
            ${{ vars.DOCKERHUB_REPOSITORY }}:${{ inputs.openfoam-version }}
            ${{ inputs.latest && format('{0}:org', vars.DOCKERHUB_REPOSITORY) || '' }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-amd64
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-arm64
          push: ${{ inputs.push }}
          target: org
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
            BUILDKIT_MULTI_PLATFORM=${{ inputs.arm64 }}
      - name: Push build cache (org, amd64)
        if: inputs.openfoam-version < 1000 && inputs.push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-amd64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-amd64,mode=max
          target: org
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
      - name: Push build cache (org, arm64)
        if: inputs.openfoam-version < 1000 && inputs.arm64 && inputs.push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-arm64
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache-${{ inputs.openfoam-version }}-arm64,mode=max
          target: org
          build-args: |
            OPENFOAM_VERSION=${{ inputs.openfoam-version }}
            UBUNTU_VERSION=${{ inputs.ubuntu-version }}
